"""add verification code fields to user model

Revision ID: 70f479c205da
Revises: bbd6e2c26bc6
Create Date: 2025-07-19 21:53:14.652363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f479c205da'
down_revision = 'bbd6e2c26bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('verification_code_expires')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
