"""Add marital status to user profiles

Revision ID: add_marital_status_001
Revises: d236f3df05e5
Create Date: 2024-07-20 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_marital_status_001'
down_revision = 'd236f3df05e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('marital_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'marital_status')
    # ### end Alembic commands ###
