"""Add profile approval system

Revision ID: add_profile_approval
Revises: ec036ae93f62
Create Date: 2024-01-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_profile_approval'
down_revision = 'ec036ae93f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # Set default values for existing records
    op.execute("UPDATE user_profiles SET is_approved = 0 WHERE is_approved IS NULL")
    
    # Make is_approved non-nullable after setting default values
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('is_approved', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_approved')
    # ### end Alembic commands ###
