"""Add JazzCash payment fields to Payment model

Revision ID: ec036ae93f62
Revises: 739e7bd7bb35
Create Date: 2025-07-20 19:13:56.774607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec036ae93f62'
down_revision = '739e7bd7bb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('jazzcash_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=mysql.ENUM('Single', 'Married', 'Divorced', 'Widowed'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Single'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('marital_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('Single', 'Married', 'Divorced', 'Widowed'),
               existing_nullable=True,
               existing_server_default=sa.text("'Single'"))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('purpose')
        batch_op.drop_column('jazzcash_number')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
