"""Remove age and income columns from user profiles

Revision ID: remove_age_income
Revises: add_cnic_field
Create Date: 2025-07-20 08:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_age_income'
down_revision = 'add_cnic_field'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('income', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
