"""Update admin table to use email instead of username

Revision ID: update_admin_table
Revises: add_profile_approval
Create Date: 2024-01-22 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'update_admin_table'
down_revision = 'add_profile_approval'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        # Add email column
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        # Increase password field size
        batch_op.alter_column('password', type_=sa.String(255))

    # If there are existing admin records, you might want to set a default email
    # For now, we'll make email nullable temporarily, then update it to be unique and not null
    
    # Create unique constraint on email
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_admin_email', ['email'])
        
    # Remove username column (after ensuring data is migrated if needed)
    # Only do this if you're sure there's no important data in username
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('username')
        
    # Make email non-nullable after setting values
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('email', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint('uq_admin_email', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')
        batch_op.alter_column('password', type_=sa.String(150))
    # ### end Alembic commands ###
